spring.application.name=news
spring.datasource.url=jdbc:mysql://localhost:3306/news
spring.datasource.username=root
spring.datasource.password=bala@2005
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
gnews.api.key=bbdc90a7f146699d655e32d8de6964aa
spring.datasource.hikari.maximum-pool-size=3